{% set name = "jupyterlab-pioneer" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_pioneer-{{ version }}.tar.gz
  sha256: da8c9194387c3b2b4057c2375364d466c94e2b51f7fa92b4ac694b9074c7e1f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_server >=2.0.1,<3

test:
  imports:
    - jupyterlab_pioneer
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/educational-technology-collective/jupyterlab-pioneer
  summary: A JupyterLab extension for generating and exporting JupyterLab event telemetry data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aktech
    - mengyanw
    - cab938
    - cmarmo
