{% set name = "jupyterlab-pioneer" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_pioneer-{{ version }}.tar.gz
  sha256: 88ad0a08b61ef796931cccbbcbb5b854d5ce657cb47e1d1b586a93fcaf1ca157

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3

test:
  imports:
    - jupyterlab_pioneer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/educational-technology-collective/jupyterlab-pioneer
  summary: A JupyterLab extension for generating and exporting JupyterLab event telemetry data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aktech
    - mengyanw
    - cab938
