{% set name = "jupyterlab-pioneer" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_pioneer-{{ version }}.tar.gz
  sha256: 35df5c085f4670975204e4d3f020d11aa2dc6645382e2ae9efdbc916c21466ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3

test:
  imports:
    - jupyterlab_pioneer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/educational-technology-collective/jupyterlab-pioneer
  summary: A JupyterLab extension for generating and exporting JupyterLab event telemetry data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aktech
    - mengyanw
    - cab938
